# For github integration, drop your ssh key in to /config/.ssh. Then open a terminal from the top menu and set your github username and email via the following commands
# git config --global user.name "username"
# git config --global user.email "email address"
---
version: "2.1"
services:
#
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    env_file: stack.env # used by portainer
    volumes:
      - ${LOCVOL1}code-server:/config
    #ports:
      #- 8099:8443
      #- 8443:8443
    restart: unless-stopped
#
#
networks:
  default:
    name: ${CONNET}
    external: true
