---
version: "2.1"
services:
#
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=${SUDOPASS} #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      #- DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ${LOCVOL1}code-server:/config
    #ports:
      #- 8099:8443
      #- 8443:8443
    restart: unless-stopped
#
#
networks:
  default:
    external:
      name: ${NETCON}
