---
version: "2.1"
services:
#
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    env_file: stack.env # used by portainer
    volumes:
      - ${LOCVOL1}code-server:/config
    #ports:
      #- 8099:8443
      #- 8443:8443
    restart: unless-stopped
#
#
networks:
  default:
    name: ${CONNET}
    external: true
