# https://docs.firefly-iii.org/firefly-iii/installation/docker/

version: '3.7'

services:
#
  app:
    image: fireflyiii/core:latest
    container_name: firefly_iii
    env_file: stack.env
    volumes:
      - ${LOCVOL1}fireflyiii/app:/var/www/html/storage/upload
    #ports:
    #  - 80:8080
    depends_on:
      - db
    restart: unless-stopped
#
  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: firefly_iii_db
    env_file: stack.env # used by portainer
    volumes:
      - ${LOCVOL1}fireflyiii/db:/config
    restart: unless-stopped
#
  #
  #
  #
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine:latest
    restart: unless-stopped
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://firefly_iii:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"
networks:
  default:
    name: ${CONNET}
    external: true