--- 
version: '3.7'
services:
#
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    env_file: stack.env # used by portainer
    volumes:
      - ${LOCVOL1}freshrss:/config
    #ports:
      #- 80:80
    restart: unless-stopped
#
networks:
  default:
    name: ${CONNET}
    external: true
