---
services:
#
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file: stack.env # used by portainer
    volumes:
      - ${LOCVOL1}jellyfin:/config
      - ${MEDIAVOL}:/data
      - ${MEDIAVOL}:/Media
    ports:
      - 8096:8096 # HTTP webUI
      - 8920:8920 #optional, HTTPS web ui
      - 7359:7359/udp #optional, Allows clients to discover Jellyfin on the local network.
      - 1900:1900/udp #optional, Service discovery used by DNLA and clients.
    restart: unless-stopped
#
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    env_file: stack.env # used by portainer
    volumes:
      - ${LOCVOL1}plex:/config
      - ${MEDIAVOL}:/MediaNFS
    ports:
      - 32400:32400 # WebUI
      #- 1900:1900/udp # Plex DLNA Server
      #- 3005:3005 # Plex Companion
      #- 5353:5353/udp # Bonjour/Avahi network discovery
      #- 8324:8324 # Plex for Roku via Plex Companion
      - 32410:32410/udp # GDM network discovery
      - 32412:32412/udp # GDM network discovery
      - 32413:32413/udp # GDM network discovery
      - 32414:32414/udp # GDM network discovery
      - 32469:32469 #  Plex DLNA Server
    restart: unless-stopped
#
networks:
  default:
    name: ${CONNET}
    external: true
