---
version: "2.1"
services:
#
  minecraft-allen:
    image: itzg/minecraft-server:java17-alpine
    container_name: minecraft-allen
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UID=${PUID}
      - GID=${PGID}
      - TYPE=${MCTYPE}
      - EULA=TRUE
      - VERSION=${MCVERSION}
      - SERVER_NAME=${MCSVRNAME}
      - LEVEL=${MCLEVEL} # world is the default
      - SEED=${MCSEED}
      - VIEW_DISTANCE=${MCVIEWDIST}
      - SNOOPER_ENABLED=false
      - MOTD=${MCMOTD}
      - OPS=${MCOPS}
      - MODE=${MCMODE}
      - PVP=false
      - MEMORY=${MCMEM}
      - USE_AIKAR_FLAGS=true
      - MODPACK=${MCMODPACK}
      - REMOVE_OLD_MODS=${MCREMOVEOLDMODS}
      - SPIGET_RESOURCES=${MCSPIGET}

    volumes:
      - ${LOCVOL1}minecraft-allen:/data
    ports:
      - 25569:25565
    restart: unless-stopped
#
# 1536 89 1812
#
networks:
  default:
    external:
      name: ${NETCON}
