#
# https://docker-minecraft-server.readthedocs.io/en/latest/variables/#general-options
# https://github.com/itzg/docker-minecraft-bedrock-server
---
services:
#
  minecraft-bedrock-a:
    image: itzg/minecraft-bedrock-server:${MCIMAGE}
    container_name: minecraft-bedrock-a
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
      - TYPE=${MCTYPE}
      - EULA=TRUE
      - VERSION=${MCVERSION} # What is our minecraft version
      - OPS=${SVROPS}
      - MEMBERS=${SVRMEMBERS}
      - VISITORS=${SVRVISITORS}
      - SERVER_NAME=${SERVER_NAME}
      - GAMEMODE=${GAMEMODE}
      - FORCE_GAMEMODE=${FORCE_GAMEMODE}
      - DIFFICULTY=${DIFFICULTY}
      - ALLOW_CHEATS=${ALLOW_CHEATS}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - ONLINE_MODE=${ONLINE_MODE}
      - WHITE_LIST=${WHITE_LIST}
      - ALLOW_LIST=${ALLOW_LIST}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_PORT_V6=${SERVER_PORT_V6}
      - ENABLE_LAN_VISIBILITY=${ENABLE_LAN_VISIBILITY}
      - VIEW_DISTANCE=${VIEW_DISTANCE}
      - TICK_DISTANCE=${TICK_DISTANCE}
      - PLAYER_IDLE_TIMEOUT=${PLAYER_IDLE_TIMEOUT}
      - MAX_THREADS=${MAX_THREADS}
      - LEVEL_NAME=${LEVEL_NAME}
      - LEVEL_SEED=${LEVEL_SEED}
      - LEVEL_TYPE=${LEVEL_TYPE}
      - DEFAULT_PLAYER_PERMISSION_LEVEL=${DEFAULT_PLAYER_PERMISSION_LEVEL}
      - TEXTUREPACK_REQUIRED=${TEXTUREPACK_REQUIRED}
      - CONTENT_LOG_FILE_ENABLED=${CONTENT_LOG_FILE_ENABLED}
      - CONTENT_LOG_LEVEL=${CONTENT_LOG_LEVEL}
      - CONTENT_LOG_CONSOLE_OUTPUT_ENABLED=${CONTENT_LOG_CONSOLE_OUTPUT_ENABLED}
      - COMPRESSION_THRESHOLD=${COMPRESSION_THRESHOLD}
      - COMPRESSION_ALGORITHM=${COMPRESSION_ALGORITHM}
      - SERVER_AUTHORITATIVE_MOVEMENT=${SERVER_AUTHORITATIVE_MOVEMENT}
      - PLAYER_POSITION_ACCEPTANCE_THRESHOLD=${PLAYER_POSITION_ACCEPTANCE_THRESHOLD}
      - PLAYER_MOVEMENT_SCORE_THRESHOLD=${PLAYER_MOVEMENT_SCORE_THRESHOLD}
      - PLAYER_MOVEMENT_ACTION_DIRECTION_THRESHOLD=${PLAYER_MOVEMENT_ACTION_DIRECTION_THRESHOLD}
      - PLAYER_MOVEMENT_DISTANCE_THRESHOLD=${PLAYER_MOVEMENT_DISTANCE_THRESHOLD}
      - PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS=${PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS}
      - CORRECT_PLAYER_MOVEMENT=${CORRECT_PLAYER_MOVEMENT}
      - SERVER_AUTHORITATIVE_BLOCK_BREAKING=${SERVER_AUTHORITATIVE_BLOCK_BREAKING}
      - SERVER_AUTHORITATIVE_BLOCK_BREAKING_PICK_RANGE_SCALAR=${SERVER_AUTHORITATIVE_BLOCK_BREAKING_PICK_RANGE_SCALAR}
      - CHAT_RESTRICTION=${CHAT_RESTRICTION}
      - DISABLE_PLAYER_INTERACTION=${DISABLE_PLAYER_INTERACTION}
      - CLIENT_SIDE_CHUNK_GENERATION_ENABLED=${CLIENT_SIDE_CHUNK_GENERATION_ENABLED}
      - BLOCK_NETWORK_IDS_ARE_HASHES=${BLOCK_NETWORK_IDS_ARE_HASHES}
      - DISABLE_PERSONA=${DISABLE_PERSONA}
      - DISABLE_CUSTOM_SKINS=${DISABLE_CUSTOM_SKINS}
      - SERVER_BUILD_RADIUS_RATIO=${SERVER_BUILD_RADIUS_RATIO}
      - ALLOW_OUTBOUND_SCRIPT_DEBUGGING=${ALLOW_OUTBOUND_SCRIPT_DEBUGGING}
      - ALLOW_INBOUND_SCRIPT_DEBUGGING=${ALLOW_INBOUND_SCRIPT_DEBUGGING}
      - FORCE_INBOUND_DEBUG_PORT=${FORCE_INBOUND_DEBUG_PORT}
      - SCRIPT_DEBUGGER_AUTO_ATTACH=${SCRIPT_DEBUGGER_AUTO_ATTACH}
      - SCRIPT_DEBUGGER_AUTO_ATTACH_CONNECT_ADDRESS=${SCRIPT_DEBUGGER_AUTO_ATTACH_CONNECT_ADDRESS}
      - SCRIPT_WATCHDOG_ENABLE=${SCRIPT_WATCHDOG_ENABLE}
      - SCRIPT_WATCHDOG_ENABLE_EXCEPTION_HANDLING=${SCRIPT_WATCHDOG_ENABLE_EXCEPTION_HANDLING}
      - SCRIPT_WATCHDOG_ENABLE_SHUTDOWN=${SCRIPT_WATCHDOG_ENABLE_SHUTDOWN}
      - SCRIPT_WATCHDOG_HANG_EXCEPTION=${SCRIPT_WATCHDOG_HANG_EXCEPTION}
      - SCRIPT_WATCHDOG_HANG_THRESHOLD=${SCRIPT_WATCHDOG_HANG_THRESHOLD}
      - SCRIPT_WATCHDOG_SPIKE_THRESHOLD=${SCRIPT_WATCHDOG_SPIKE_THRESHOLD}
      - SCRIPT_WATCHDOG_SLOW_THRESHOLD=${SCRIPT_WATCHDOG_SLOW_THRESHOLD}
      - SCRIPT_WATCHDOG_MEMORY_WARNING=${SCRIPT_WATCHDOG_MEMORY_WARNING}
      - SCRIPT_WATCHDOG_MEMORY_LIMIT=${SCRIPT_WATCHDOG_MEMORY_LIMIT}
      - OP_PERMISSION_LEVEL=${OP_PERMISSION_LEVEL}
      - EMIT_SERVER_TELEMETRY=${EMIT_SERVER_TELEMETRY}
      - MSA_GAMERTAGS_ONLY=${MSA_GAMERTAGS_ONLY}
      - ITEM_TRANSACTION_LOGGING_ENABLED=${ITEM_TRANSACTION_LOGGING_ENABLED}
    stdin_open: true
    tty: true
    volumes:
      - ${LOCVOL1}minecraft-bedrock-a:/data
    ports:
      - 19132:19132
      - 19132:19132/udp
    restart: unless-stopped
#
# 1536 89 1812
#
networks:
  default:
    name: ${CONNET}
    external: true

#
#
#PUID=1000
#PGID=1000
#TZ=America/Los_Angeles
#LOCVOL1=/volume2/docker-ssd/
#LOCVOL2=
#NETCON=dbridge
#MCTYPE=PAPER
#MCVERSION=1.18.2
#MCSVRNAME=Home Server
#MCLEVEL=world
#MCSEED=3612259
#MCVIEWDIST=16
#MCMOTD=MC Server
#MCMODE=survival
#MCPVP=false
#MCMEM=4G
#MCOPS=Fincher_
#MCMODPACK=null
#MCREMOVEOLDMODS=TRUE
#MCSPIGET=null
