---
version: "2.1"
services:
#
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MENU_VERSION=1.9.9 #optional
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
    volumes:
      - ${LOCVOL1}netbootxyz:/config
      - ${LOCVOL1}netboot:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8989:80 #optional
    restart: unless-stopped
#
#
networks:
  default:
    name: ${CONNET}
    external: true
