--- 
services:
#
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
#
networks:
  default:
    name: ${CONNET}
    external: true