---
version: "2.1"
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    #cap_add:
      #- NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}npm:/data
      - ${LOCVOL1}npm-certs:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80
      - 10081:81
    networks: # networks are processed in lexical order
      0hostnet: # process this one before any other network
        ipv4_address: 192.168.1.4
      default:
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
#
#
networks:
  0hostnet:
    external: true
    name: ${NETHOST}
  default:
    external: true
    name: ${NETCON}
