---
version: "2.1"
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}npm:/data
      - ${LOCVOL1}npm-certs:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80
      - 10081:81
    networks:
      directnet:
        ipv4_address: ${REVPROXYIP}
      default:
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
#
#
networks:
  directnet:
    external:
    name: ${NETHOST}
  default:
    external:
    name: ${NETCON}
