#
# https://nginxproxymanager.com/setup/#using-mysql-mariadb-database
#
--- 
version: '3.7'
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    cap_add:
      - NET_ADMIN
    env_file: stack.env # used by portainer
    volumes:
      - ${LOCVOL1}npm/app:/data
      - ${LOCVOL1}npm/certs:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80
      - 10081:81 # NPM admin interface
      - 12001-12020:12001-12020 # for rr stack
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    networks:
      alphanet:
        ipv4_address: 192.168.1.6
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    depends_on:
      - db
#
  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: npm-db
    env_file: stack.env # used by portainer
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB_MYSQL_NAME} #optional
      - MYSQL_USER=${DB_MYSQL_USER} #optional
      - MYSQL_PASSWORD=${DB_MYSQL_PASSWORD} #optional
    volumes:
      - ${LOCVOL1}npm/db:/config
    #ports:
      #- 3306:3306
    restart: unless-stopped
#
networks:
  default:
    name: ${CONNET}
    external: true
  alphanet:
    name: ${MACNET}
    external: true
