---
version: "2.1"
services:
#
  pihole1:
    image: pihole/pihole:latest
    container_name: pihole1
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBPASSWORD=${SUDOPASS}
      - SERVERIP=${PIHOLE1IP}
      - DNSMASQ_USER=root
      - WEBTHEME=default-dark
#      - TEMPERATUREUNIT=f
#      - PIHOLE_DNS_=192.168.1.11;192.168.1.12
    volumes:
      - ${LOCVOL1}pihole1:/etc/pihole
#      - ${LOCVOL1}pihole1/config/resolv.conf:/etc/resolv.conf
#      - ${LOCVOL1}pihole1/config/dnsmasq.d:/etc/dnsmasq.d
    ports:
      - 3080:80
      - 53:53
      - 53:53/udp
    restart: unless-stopped
    networks:
      directnet:
        ipv4_address: ${PIHOLE1IP}
#
#
networks:
  directnet:
    external: true
    name: ${NETHOST}