---
version: "2.1"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LOCVOL1}portainer:/data
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    restart: unless-stopped

networks:
  default:
    external:
      name: ${CONNET}
# docker run -d -p 8000:8000 -p 9000:9000 -p 9443:9443 \
# --name=portainer --restart=always --pull=always \
# -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ee:latest
