---
version: "2.1"
services:
#
  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    restart: always
#
#
#networks:
#  default:
#    name: dbr0
#    external: true
