---
version: "2.1"
services:
#
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}heimdall:/config
    #ports:
      #- 52080:80
      #- 52443:443
    restart: unless-stopped
#
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}mariadb:/config
    #ports:
      #- 3306:3306
    restart: unless-stopped
#
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      #- DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ${LOCVOL1}code-server:/config
    #ports:
      #- 8099:8443
      #- 8443:8443
    restart: unless-stopped
#
#
networks:
  default:
    external:
      name: ${NETCON}
