---
version: "2.1"
services:
#
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}heimdall:/config
    #ports:
      #- 52080:80
      #- 52443:443
    restart: unless-stopped
#
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}mariadb:/config
    #ports:
      #- 3306:3306
    restart: unless-stopped
#
  nginx:
    image: lscr.io/linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}nginx:/config
      - ${LOCVOL1}code-server/workspace/dev-js:/config/www-devjs #javascript workspace code-server connector
    #ports:
      #- 80:80
      #- 443:443
    restart: unless-stopped
#
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PMA_ARBITRARY=1 #optional
      - PMA_ABSOLUTE_URI=https://phpmyadmin.finchhome.xyz #optional
    volumes:
      - ${LOCVOL1}phpmyadmin:/config
    #ports:
      #- 80:80
    restart: unless-stopped
#
#
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}syncthing:/config
      - ${LOCVOL1}syncthing-data1:/data1
      - ${LOCVOL1}syncthing-data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
#
#
networks:
  default:
    external:
      name: ${NETCON}
