---
version: "2.1"
services:
#
  sftp:
    image: atmoz/sftp:alpine
    container_name: sftp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}sftp/configs/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ${LOCVOL1}sftp/configs/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ${LOCVOL1}sftp/configs/users.conf:/etc/sftp/users.conf:ro
      - ${LOCVOL1}sftp/uploads:/home
    ports:
      - 2222:22
    restart: unless-stopped
#
#
#
networks:
  default:
    name: ${CONNET}
    external: true