#
# https://github.com/louislam/uptime-kuma?tab=readme-ov-file
#
---
services:
#
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}uptime-kuma:/app/data
    ports:
      - 3002:3001 # 3001 is already in use
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
#
#
#
networks:
  default:
    name: ${CONNET}
    external: true