---
version: "3"
#networks:
#  loki:
services:
  loki:
    container_name: loki
    image: grafana/loki:2.4.2
    volumes:
      #- ${LOCVOL1}loki:/etc/loki
      - ${LOCVOL1}loki/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    restart: unless-stopped
    #command: -config.file=/etc/loki/loki-config.yml
    #networks:
      #- loki
  promtail:
    container_name: promtail
    image: grafana/promtail:2.4.2
    volumes:
      - /var/log:/var/log
      - ${LOCVOL1}promtail:/etc/promtail
    ports:
      - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    #networks:
      #- loki
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: ${PUID}
    volumes:
    - ${LOCVOL1}grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    #networks:
      #- loki
#
#
networks:
  default:
    external:
      name: ${NETCON}